reg_lut = [
    ["x0", 	"zero", "hardwired to 0, ignores writes "],
    ["x1", 	"ra",	"return address for jumps "],
    ["x2", 	"sp", 	"stack pointer "],
    ["x3", 	"gp", 	"global pointer "],
    ["x4", 	"tp", 	"thread pointer "],
    ["x5", 	"t0", 	"temporary register 0 "],
    ["x6", 	"t1", 	"temporary register 1 "],
    ["x7", 	"t2", 	"temporary register 2 "],
    ["x8", 	"s0",	"saved register 0 or frame pointer(fp) "],
    ["x9", 	"s1", 	"saved register 1 "],
    ["x10", "a0", 	"return value or function argument 0 "],
    ["x11", "a1", 	"return value or function argument 1 "],
    ["x12", "a2", 	"function argument 2 "],
    ["x13", "a3", 	"function argument 3 "],
    ["x14", "a4", 	"function argument 4 "],
    ["x15", "a5", 	"function argument 5 "],
    ["x16", "a6", 	"function argument 6 "],
    ["x17", "a7", 	"function argument 7 "],
    ["x18", "s2", 	"saved register 2 "],
    ["x19", "s3", 	"saved register 3 "],
    ["x20", "s4", 	"saved register 4 "],
    ["x21", "s5", 	"saved register 5 "],
    ["x22", "s6", 	"saved register 6 "],
    ["x23", "s7", 	"saved register 7 "],
    ["x24", "s8", 	"saved register 8 "],
    ["x25", "s9", 	"saved register 9 "],
    ["x26", "s10", 	"saved register 10 "],
    ["x27", "s11", 	"saved register 11 	"],
    ["x28", "t3", 	"temporary register 3 "],
    ["x29", "t4", 	"temporary register 4 "],
    ["x30", "t5", 	"temporary register 5 "],
    ["x31", "t6", 	"temporary register 6 "],
    ["pc", 	"none",	"program counter "]
]

tests = ["riscv_arithmetic_basic_test",
        "riscv_rand_instr_test",
        "riscv_jump_stress_test",
        "riscv_loop_test",
        "riscv_rand_jump_test",
        "riscv_mmu_stress_test",
        "riscv_no_fence_test",
        "riscv_illegal_instr_test",
        "riscv_ebreak_test",
        "riscv_ebreak_debug_mode_test",
        "riscv_full_interrupt_test",
        "riscv_csr_test",
        "riscv_unaligned_load_store_test"]